version: '3'
services:
  python-app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - mongodb_service

  mongodb_service:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes: 
      - db-data:/data/db

volumes:
  db-data: